[providers]
  node = true

[phases.setup]
  nixPkgs = ["ffmpeg", "python3"]
  cmds = [
    "curl -L https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
    "chmod a+rx /usr/local/bin/yt-dlp"
  ]
